# name: Deploy to Vercel

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#       with:
#         fetch-depth: 0
#     - name: Install Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14'
#     - run: npm install
#     - run: npm run build
#     - name: Install Vercel CLI
#       run: npm install -g vercel
#     - name: Deploy to Vercel
#       env:
#         VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#         VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#         VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
#       run: vercel --prod --token $VERCEL_TOKEN --confirm --scope $VERCEL_ORG_ID
